apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <rose-gardenのURL>
    targetRevision: main
    path: apps/keycloak-operator/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
