apiVersion: v1
data:
  iris.toml: |
    host = "iris.harulinwu.me"

    [ingest]
    dir = "/app/iris-storage"
    listen = "0.0.0.0:80"
    cors_origin = [
      "https://iris.harulinwu.me",
      "https://iris-public.i.f4n.dev",
    ]

    [image.sizes.icon]
    width = 64
    height = 64
    format = "webp"

    [image.sizes.thumbnail]
    width = 320
    height = 320
    format = "webp"

    [image.sizes.main]
    width = 2560
    height = 1440
    format = "png"
kind: ConfigMap
metadata:
  name: iris-toml
