apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: huggingface-local-cache
  namespace: vllm
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: huggingface-local
  volumeMode: Filesystem
  volumeName: huggingface-local-cache
