apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coredns
  name: coredns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coredns
  strategy: {}
  template:
    metadata:
      labels:
        app: coredns
    spec:
      volumes:
        - name: config
          configMap:
            name: coredns-config
        - name: ext-managed-config
          configMap:
            name: f4n-dev-zone
      containers:
        - name: coredns
          image: coredns/coredns:1.14.1
          imagePullPolicy: IfNotPresent
          args: ["-conf", "/etc/coredns/Corefile"]
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config
              subPath: Corefile
              mountPath: /etc/coredns/Corefile
            - name: config
              subPath: i.f4n.dev.zone
              mountPath: /zones/i.f4n.dev.zone
            - name: ext-managed-config
              subPath: p.f4n.dev.zone
              mountPath: /zones/p.f4n.dev.zone
            - name: ext-managed-config
              subPath: a.f4n.dev.zone
              mountPath: /zones/a.f4n.dev.zone
