apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: soil
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/loxygenK/home-garden
    targetRevision: main
    path: apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
