apiVersion: k8s.keycloak.org/v2beta1
kind: KeycloakRealmImport
metadata:
  name: gardener
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    realm: gardener
    enabled: true
    displayName: "Gardeners"
    sslRequired: external

    users:
      - username: flisan
        enabled: true
        emailVerified: true
        credentials:
          - type: password
            value: "changeme-please"
            temporary: true
        realmRoles:
          - offline_access
          - uma_authorization

    clients:
      - clientId: pve
        name: "Proxmox VE"
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris:
          - "https://pve.i.f4n.dev/*"
        webOrigins:
          - "https://pve.i.f4n.dev"
        standardFlowEnabled: true
        directAccessGrantsEnabled: false

      - clientId: grafana
        name: "Grafana"
        enabled: true
        protocol: openid-connect
        publicClient: false
        secret: "pve-client-secret-changeme"
        redirectUris:
          - "https://grafana.i.f4n.dev/*"
        webOrigins:
          - "https://grafana.i.f4n.dev"
        standardFlowEnabled: true
        directAccessGrantsEnabled: false

      - clientId: headlamp
        name: "Headlamp"
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris:
          - "https://k3s.i.f4n.dev/*"
        webOrigins:
          - "https://k3s.i.f4n.dev"
        standardFlowEnabled: true
        directAccessGrantsEnabled: false
