apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-iris-dir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
  storageClassName: local-storage
  volumeMode: Filesystem
  volumeName: iris-hdd-private
